name: Build engine images and publish

on:
  push:
    branches:
      - main

jobs:

  find-configurations:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Find configurations
        id: find-targets
        run: |
          configures=$(git diff --name-only HEAD^...HEAD -- configures | grep -e "\.json" | xargs -I{e} echo \"{e}\" | tr '\n' ',' | sed 's/,$//')
          echo "configures=[${configures}]" >> ${GITHUB_OUTPUT}
      
    outputs:
      configures: ${{ steps.find-targets.outputs.configures }}

  build-and-publish:
    needs:
      - find-configurations

    if: needs.find-configurations.outputs.configures != '[]'

    strategy:
      matrix:
        configure: ${{ fromJson(needs.find-configurations.outputs.configures) }}
    uses: ./.github/workflows/build.yaml
    with:
      configuration: ${{ matrix.configure }}
      registry: ghcr.io
      repo: kupl/kaprese-engines
